name: 'GZoltar Feedback'
description: 'Analyzes GZoltar results and posts a comment on the pull request/commit with the suspicious lines.'
inputs:
  token:
    description: >
      Personal access token (PAT) used to make actions on the repository such as creating comments on PRs/Commits. 
      It is recommended to use a service account with the least permissions necessary. 
      Also when generating a new PAT, select the least scopes necessary. 
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  build-path:
    description: 'Path to the build/target directory containing the GZoltar results'
    default: '/build'
  serialized-coverage-file-path:
    description: 'Path to the file containing the serialized file with the coverage collect by GZoltar. Example: `/build/gzoltar.ser`'
    required: false
  test-cases-file-path:
    description: 'Path to the file containing a list of all test cases generated by GZoltar. Example: `/build/sfl/txt/tests.csv`'
    required: false
  spectra-file-path:
    description: 'Path to the file containing a list of all lines of code identified by GZoltar (one per row) of all classes under test. Example: `/build/sfl/txt/spectra.csv`'
    required: false
  matrix-file-path:
    description: 'Path to the file containing a binary coverage matrix produced by GZoltar. Example: `/build/sfl/txt/matrix.txt`'
    required: false
  statistics-file-path:
    description: 'Path to the file containing statistics information of the ranking produced by GZoltar. Example: `/build/sfl/txt/statistics.csv`'
    required: false
  ranking-files-paths:
    description: 'Path to each SFL ranking algorithms file. Example: `[/build/sfl/txt/ochiai.ranking.csv]`'
    required: false
  sfl-ranking:
    description: 'List of the SFL ranking algorithms to use separated by `,`. (Keep in mind that each algorithm need to have present a fault localization report file in the `ranking-files-path` directory with his name, i.e. `ochiai.ranking.csv`.)'
    default: '[ochiai]'
  sfl-threshold:
    description: 'Line suspiciousness threshold to trigger an warning. A threshold is needed for each SFL ranking algorithms used'
    default: '[0.5]'
  upload-artifacts:
    description: 'Indicates whether to upload the GZoltar results as an artifact'
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'